# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BootswatchTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=400, verbose_name='Theme')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bootswatch_theme', to='sites.Site')),
            ],
            options={
                'verbose_name': 'theme',
                'verbose_name_plural': 'themes',
            },
        ),
    ]
